export default {
  SET_STATE: 'user/SET_STATE',
  SET_PROFILE: 'user/SET_PROFILE',
  SET_BUFFER: 'user/SET_BUFFER',
  GET_CURRENT_USER: 'user/GET_CURRENT_USER',
  GET_CHECKPOINT: 'user/GET_CHECKPOINT',
  GET_PROGRESS: 'user/GET_PROGRESS',
  TOGGLE_POPUP: 'user/TOGGLE_POPUP'
};
