{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fe-umkm-revamp.serviceAccountName" . }}
  labels:
{{ include "fe-umkm-revamp.labels" . | nindent 4 }}
{{- end -}}
